### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/infografia-DuilioAquino10-1#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-DuilioAquino10-1/files/8054885/INFOGRAFIA.pdf)

**Comment by IsaHuerta23** [comment]
Calificación: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
